config/routes.rb
Rails.application.routes.draw do
  resources :users
  namespace :api do 
    resources :sensors, only: [] do
      resources :measurements, only: [:create]
    end
  end

  namespace :admin do
    root to: 'sensor_types#index'
    resources :sensor_types
    resources :sensors
  end
  get 'index', :to => 'main#index'
  get 'signup', :to => 'main#signup'
  post 'signup', :to => 'main#create' 
  root :to => "main#index"

  namespace :dashboard do 
    root to: 'plants#index'
    resources :plants do
      get :associate_sensors, on: :collection
    end
  end
end

app/models/plant.rb
class Plant < ActiveRecord::Base

  has_many :sensors
  mount_uploader :timelapse, TimelapseUploader

  def images
    if @images.nil?
      @images = Image.where(sensor_id: camera_ids)
    end
    @images
  end

  def camera_ids
    @camera_ids ||= sensors.cameras.pluck(:id)
  end

  def generate_timelapse
    image_list = QuickMagick::ImageList.new
    images = self.images.where('created_at BETWEEN ? AND ?', Time.now - 3.minutes, Time.now)

    if images.any?
      images.each do |image|
        image_list << QuickMagick::Image.read(image.file.path)
      end
      image_list.format = 'gif'
      tmp_path = Rails.root.join('tmp',"#{Time.now.to_i}.gif")
      image_list.save(tmp_path.to_s)
      
      File.open(tmp_path) do |file|
        update_attribute(:timelapse, file)
      end
      
      File.delete(tmp_path)
    end    
  end

  def chart_data(start_time, end_time)
    series = []
    labels = (start_time.to_i..end_time.to_i).step(1.minute)
    self.sensors.each do |sensor|
      if !sensor.sensor_type.sensor_type.camera?
        key = sensor.sensor_type_text
        values = sensor.measurements.where('created_at BETWEEN ? AND ?', start_time, end_time).order(:created_at).pluck(:value)
        Rails.logger.info "[INFO] values are: #{values.inspect}"
        series << {
          name: key,
          data: values
        }
      end
    end
    {
      labels: labels,
      series: series
    }
  end


end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  layout 'dashboard'
end

app/controllers/dashboard/plants_controller.rb
class Dashboard::PlantsController < Dashboard::BaseController

  def index
    @plants = Plant.all
  end

  def show
    @plant = Plant.find(params[:id])
    @plant.generate_timelapse
    start_time = Time.now - 30.minutes
    end_time = Time.now
    @images = @plant.images.where('created_at BETWEEN ? AND ?', start_time, end_time).order(created_at: :desc)
    gon.chart_data = @plant.chart_data(start_time, end_time)
  end

  def associate_sensors
    @plant = Plant.find_or_create_by(name: 'Alba')
    Sensor.update_all(plant_id: @plant.id)
    redirect_to 'https://www.youtube.com/watch?v=rLw-9dpHtcU'
  end
end

app/helpers/dashboard/base_helper.rb
module Dashboard::BaseHelper
end

app/helpers/dashboard/plants_helper.rb
module Dashboard::PlantsHelper
end

app/views/dashboard/plants/index.html.haml
.page-header
  %h1 Mis plantaas
.row
  - @plants.each do |plant|
    .col-sm-4.col-md-3
      .pot      
        = link_to dashboard_plant_url(plant) do
          %span.thumb
            %i.icon-leaf
          %span.name
            %span= plant.name

app/views/dashboard/plants/show.html.haml
- content_for :javascripts do 
  = javascript_include_tag 'dashboard/plants/show'
.page-header
  %h1= @plant.name
.row
  .col-sm-8
    #plant-chart.ct-chart(style="height: 500px;")
  .col-sm-4
    = image_tag @plant.timelapse.url, class: 'img-responsive'
- if @plant.images.any?
  .row.space-top
    - @images.each do |image|
      .col-sm-4.col-md-3
        = image_tag image.file.url, class: 'img-responsive img-thumbnail'
        %span= l(image.created_at, format: :short)
- else
  %p.well.text-center No se han encontrado im&aacute;genes