config/routes.rb
Rails.application.routes.draw do
  resources :users
  namespace :api do 
    resources :sensors, only: [] do
      resources :measurements, only: [:create]
    end
  end

  namespace :admin do
    root to: 'sensor_types#index'
    resources :sensor_types
    resources :sensors
  end
  get 'index', :to => 'main#index'
  get 'signup', :to => 'main#signup'
  post 'signup', :to => 'main#create' 
  root :to => "main#index"

  namespace :dashboard do 
    root to: 'plants#index'
    resources :plants do
      get :associate_sensors, on: :collection
    end
  end
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base

  delegate :sensor_type_text, to: :sensor_type
  delegate :vendor, to: :sensor_type

  belongs_to :sensor_type
  belongs_to :plant

  has_many :images
  has_many :measurements

  scope :cameras, ->{ includes(:sensor_type).where(sensor_types: { sensor_type: :camera }) }
end

app/models/sensor_type.rb
class SensorType < ActiveRecord::Base
  extend Enumerize

  enumerize :sensor_type, in: [:temperature, :soil_moisture, :water_level, :camera]

  validates :vendor, :sensor_type, :units, presence: true
  
end

app/controllers/admin/sensors_controller.rb
class Admin::SensorsController < Admin::BaseController

  params_for :sensor, :sensor_type_id, :serial_number

  before_filter :set_sensor_types, only: [:new, :edit]

  def index
    @sensors = Sensor.page(params[:page])
  end

  def new
    @sensor = Sensor.new
    Rails.logger.info "[INFO] #{@sensor_types.inspect}"
  end

  def create
    @sensor = Sensor.new(sensor_params)

    if @sensor.save
      redirect_to admin_sensors_url, notice: 'El sensor se ha agregado'
    else
      set_sensor_types
      render action: 'new'
    end
  end

  def edit
    @sensor = Sensor.find(params[:id])
  end

  def update
    @sensor = Sensor.find(params[:id])

    if @sensor.update_attributes(sensor_params)
      redirect_to admin_sensors_url, notice: 'El sensor se ha actualizado'
    else
      set_sensor_types
      render action: 'edit'
    end
  end

  def destroy
    @sensor = Sensor.find(params[:id])
    @sensor.destroy
    redirect_to admin_sensors_url, notice: 'El sensor se ha eliminado'
  end

  protected
    def set_sensor_types
      @sensor_types = SensorType.order(:sensor_type)
    end
end

app/helpers/admin/sensors_helper.rb
module Admin::SensorsHelper
end

app/views/admin/sensors/_form.html.haml
= simple_form_for [:admin, @sensor] do |f|
  = f.input :serial_number, placeholder: :translate
  = f.input :sensor_type_id, collection: @sensor_types, prompt: true, label_method: :sensor_type_text
  .text-right 
    = f.button :submit

app/views/admin/sensors/edit.html.haml
.page-header
    %h1 Editar tipo de sensor
= render 'form'

app/views/admin/sensors/index.html.haml
.page-header
    %h1 Sensores
- if @sensors.any?
    .table-responsive
        %table.table.table-striped
            %thead
                %tr
                    %th Id
                    %th Tipo de Sensor
                    %th Marca
                    %th N&uacute;mero de serie                    
                    %th 
            %tbody
                - @sensors.each do |sensor|
                    %tr
                        %td= sensor.id
                        %td= sensor.sensor_type_text
                        %td= sensor.vendor
                        %td= sensor.serial_number
                        %td
                            = link_to 'Editar', edit_admin_sensor_url(sensor), :class => 'btn btn-default btn-sm'
                            = link_to 'Eliminar', admin_sensor_url(sensor), data: {method: :delete, confirm: '¿Estás seguro?'}, :class => 'btn btn-sm btn-danger'
        = pagination(@sensors) 
- else
    %p.well
        No se han encontrado sensores                    
%p.text-right
    = link_to 'Agregar', new_admin_sensor_url, :class => 'btn btn-primary'

app/views/admin/sensors/new.html.haml
.page-header
    %h1 Agregar tipo de sensor
= render 'form'