config/routes.rb
Rails.application.routes.draw do
  resources :users
  namespace :api do 
    resources :sensors, only: [] do
      resources :measurements, only: [:create]
    end
  end

  namespace :admin do
    root to: 'sensor_types#index'
    resources :sensor_types
    resources :sensors
  end
  get 'index', :to => 'main#index'
  get 'signup', :to => 'main#signup'
  post 'signup', :to => 'main#create' 
  root :to => "main#index"

  namespace :dashboard do 
    root to: 'plants#index'
    resources :plants do
      get :associate_sensors, on: :collection
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :sensor
  mount_uploader :file, ImagesUploader
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base

  belongs_to :sensor

  validates :value, numericality: true 


end

app/models/plant.rb
class Plant < ActiveRecord::Base

  has_many :sensors
  mount_uploader :timelapse, TimelapseUploader

  def images
    if @images.nil?
      @images = Image.where(sensor_id: camera_ids)
    end
    @images
  end

  def camera_ids
    @camera_ids ||= sensors.cameras.pluck(:id)
  end

  def generate_timelapse
    image_list = QuickMagick::ImageList.new
    images = self.images.where('created_at BETWEEN ? AND ?', Time.now - 3.minutes, Time.now)

    if images.any?
      images.each do |image|
        image_list << QuickMagick::Image.read(image.file.path)
      end
      image_list.format = 'gif'
      tmp_path = Rails.root.join('tmp',"#{Time.now.to_i}.gif")
      image_list.save(tmp_path.to_s)
      
      File.open(tmp_path) do |file|
        update_attribute(:timelapse, file)
      end
      
      File.delete(tmp_path)
    end    
  end

  def chart_data(start_time, end_time)
    series = []
    labels = (start_time.to_i..end_time.to_i).step(1.minute)
    self.sensors.each do |sensor|
      if !sensor.sensor_type.sensor_type.camera?
        key = sensor.sensor_type_text
        values = sensor.measurements.where('created_at BETWEEN ? AND ?', start_time, end_time).order(:created_at).pluck(:value)
        Rails.logger.info "[INFO] values are: #{values.inspect}"
        series << {
          name: key,
          data: values
        }
      end
    end
    {
      labels: labels,
      series: series
    }
  end


end

app/models/sensor.rb
class Sensor < ActiveRecord::Base

  delegate :sensor_type_text, to: :sensor_type
  delegate :vendor, to: :sensor_type

  belongs_to :sensor_type
  belongs_to :plant

  has_many :images
  has_many :measurements

  scope :cameras, ->{ includes(:sensor_type).where(sensor_types: { sensor_type: :camera }) }
end

app/models/sensor_type.rb
class SensorType < ActiveRecord::Base
  extend Enumerize

  enumerize :sensor_type, in: [:temperature, :soil_moisture, :water_level, :camera]

  validates :vendor, :sensor_type, :units, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_confirmation_of :password
  validates_presence_of :email
  validates_presence_of :username
  validates_presence_of :password
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  before_save :encrypt_password
  has_many :plants
  
  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
  
  def self.authenticate(username, password)
  
  end
  attr_accessor :password
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
end

app/controllers/admin/sensors_controller.rb
class Admin::SensorsController < Admin::BaseController

  params_for :sensor, :sensor_type_id, :serial_number

  before_filter :set_sensor_types, only: [:new, :edit]

  def index
    @sensors = Sensor.page(params[:page])
  end

  def new
    @sensor = Sensor.new
    Rails.logger.info "[INFO] #{@sensor_types.inspect}"
  end

  def create
    @sensor = Sensor.new(sensor_params)

    if @sensor.save
      redirect_to admin_sensors_url, notice: 'El sensor se ha agregado'
    else
      set_sensor_types
      render action: 'new'
    end
  end

  def edit
    @sensor = Sensor.find(params[:id])
  end

  def update
    @sensor = Sensor.find(params[:id])

    if @sensor.update_attributes(sensor_params)
      redirect_to admin_sensors_url, notice: 'El sensor se ha actualizado'
    else
      set_sensor_types
      render action: 'edit'
    end
  end

  def destroy
    @sensor = Sensor.find(params[:id])
    @sensor.destroy
    redirect_to admin_sensors_url, notice: 'El sensor se ha eliminado'
  end

  protected
    def set_sensor_types
      @sensor_types = SensorType.order(:sensor_type)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include ParamsFor
  protect_from_forgery with: :exception

end

app/controllers/concerns/params_for.rb
module ParamsFor

  extend ActiveSupport::Concern

  module ClassMethods
    def params_for(model, *attributes)
      return if method_defined? "#{model}_params"

      define_method "#{model}_params" do
        params.require(model).permit attributes
      end
      private "#{model}_params"
    end
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  layout 'dashboard'
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  params_for :user, :username, :password, :password_confirmation, :email
  
  def index
    
  end
  
  def signup
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver
      render 'signup_success'
    else
      render 'signup'
    end
  end
    
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/sensor_types_helper.rb
module Admin::SensorTypesHelper
end

app/helpers/admin/sensors_helper.rb
module Admin::SensorsHelper
end

app/helpers/api/measurements_helper.rb
module Api::MeasurementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pagination(collection, options={})
    will_paginate collection, options.merge(renderer: BootstrapPagination::Rails)
  end

end

app/helpers/dashboard/base_helper.rb
module Dashboard::BaseHelper
end

app/helpers/dashboard/plants_helper.rb
module Dashboard::PlantsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %title Plantaas | Admin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags 
  %body
    .navbar.navbar-inverse.navbar-static-top(role="navigation")
      .container
        .navbar-header
          %button.navbar-toggle{data: {toggle: 'collapse', target: '#navbar-collapse'}}
            %i.icon-reorder
          = link_to 'Plantaas', '#', :class => 'navbar-brand'
        .collapse.navbar-collapse#navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'Tipos de Sensores', admin_sensor_types_url
            %li= link_to 'Sensores', admin_sensors_url
    .container    
      = yield

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Plantaas
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags 
  %body
    .navbar.navbar-inverse.navbar-static-top(role="navigation")
      .container
        .navbar-header
          %button.navbar-toggle{data: {toggle: 'collapse', target: '#navbar-collapse'}}
            %i.icon-reorder
          = link_to 'Plant.io', '#', :class => 'navbar-brand'
        .collapse.navbar-collapse#navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'Login', 'signup'
            %li= link_to 'Signup', 'signup'
    .container
      = yield

app/views/layouts/dashboard.html.haml
!!! 5
%html
  %head
    %title Plantaas | Admin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = yield :javascripts
    = csrf_meta_tags 
    = include_gon
  %body
    .navbar.navbar-inverse.navbar-static-top(role="navigation")
      .container
        .navbar-header
          %button.navbar-toggle{data: {toggle: 'collapse', target: '#navbar-collapse'}}
            %i.icon-reorder
          = link_to 'Plantaas', dashboard_root_url, :class => 'navbar-brand'
        .collapse.navbar-collapse#navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            / %li= link_to 'Tipos de Sensores', admin_sensor_types_url
            / %li= link_to 'Sensores', admin_sensors_url
    .container    
      = yield